CREATE TABLE patients (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    date_of_birth date,
    PRIMARY KEY (id)
);


CREATE TABLE medical_hestories(
    id int GENERATED BY DEFAULT AS IDENTITY,
    admitted_at timestamp,
    patients_id INT REFERENCES patients(id),
    status varchar(100),
     PRIMARY KEY (id)
);



CREATE TABLE invoices(
    id int GENERATED BY DEFAULT AS IDENTITY,
    total_amount decimal,
    generated_at timestamp,
    payed_at timestamp,
    medical_history_id INT REFERENCES medical_hestories(id),
    PRIMARY KEY (id)
);